services:
  db:
    image: postgres:15-alpine
    container_name: glowly-postgres
    restart: always
    environment:
      POSTGRES_DB: glowly_db
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - glowly-network

  api:
    build: .
    container_name: glowly-backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - glowly-network

volumes:
  postgres_data:

networks:
  glowly-network:

