server:
  port: ${SERVER_PORT:8080}

resend:
  resend-api-key: ${RESEND_API_KEY}

app:
  frontend-url: ${APP_FRONTEND_URL:http://localhost:3000}
  swagger-url: ${APP_SWAGGER_URL:http://localhost:8080}
  max-requests-per-minutes: ${APP_MAX_REQUESTS_PER_MINUTES:40}
  trusted-proxies: ${APP_TRUSTED_PROXIES:}

  sign:
    min-fullname-length: ${APP_MIN_FULLNAME_LENGTH:7}
    min-username-length: ${APP_MIN_USERNAME_LENGTH:4}
    max-username-length: ${APP_MAX_USERNAME_LENGTH:20}
    min-password-length: ${APP_MIN_PASSWORD_LENGTH:6}
    max-password-length: ${APP_MAX_PASSWORD_LENGTH:30}
    max-attempts: ${APP_MAX_ATTEMPTS:5}
    lockout-minutes: ${APP_LOCKOUT_MINUTES:5}

  password-recovery:
    token-expiration-minutes: ${APP_TOKEN_EXPIRATION_MINUTES:5}

jwt:
  jwt-secret: ${SPRING_JWT_SECRET}
  jwt-expiration-days: ${SPRING_JWT_EXPIRATION_DAYS:7}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:org.postgresql.Driver}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        fetch_size: 50